Feature: Migrator w/ CockroachDB support
LUSHDigital/microservice-db-golang pull request #1
Opened 2018-03-28 13:00 UTC by mnzt

From https://github.com/LUSHDigital/microservice-core-golang/pull/15

2018-03-28 13:51 UTC, mnzt commented
This using `strings.Builder` means it requires go1.10+. Is this something we are happy about, or do we wish to support past Go versions?

2018-03-28 14:38 UTC, codingconcepts commented on migrate/migrate.go
> +	conn.WriteString(co.protocol)
Still think this bit could be done more concisely with a cheeky `fmt.Sprintf("%s://...")` :P

2018-03-28 14:39 UTC, codingconcepts approved these changes
LGTM mate.  Only point is the same point I made yesterday.  I think I was outgunned by everyone though :P

2018-03-28 15:12 UTC, ladydascalie requested changes
We need vendoring!

`dep ensure` this project and commit the vendor folder!

2018-04-03 08:35 UTC, mnzt commented
@ladydascalie Vendoring added via `dep`

2018-04-03 08:57 UTC, ladydascalie approved these changes

2018-04-03 09:00 UTC, merged